apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myweb-deploy  
spec:
  replicas: 1
  selector:
    matchLabels:
        env: production

  template:
    metadata:
     name: myweb-pod
     labels:
       env: production
       dc: "2"
       region: IN
    spec:
     containers:
      - name: myweb-con
        image: d1031/web-server:v1	
        volumeMounts:
          - name: web-vol1
            mountPath: /var/www/html
     volumes:
      - name: web-vol1
        persistentVolumeClaim:
          claimName: deploy-pvc1
