apiVersion: v1
kind: Service
metadata:
  name: webtest
  labels:
    app: webtest
spec:
  ports:
  - port: 80
    nodePort: 31550
  selector:
     env: production
     dc: "2"
  type: NodePort
